project:
  type: website
  output-dir: docs

website:
  title: "IDEANet"
  navbar:
    left:
      - text: Home
        file: index.qmd
      - text: R Vignette
        file: vignette.qmd
      - text: Contact Us
        file: contact_us.qmd
        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

