project:
  type: website
  output-dir: docs

website:
  title: "IDEANet"
  back-to-top-navigation: True
  navbar:
    pinned: True
    left:
      - text: Home
        file: index.qmd
      - file: vignette.qmd
      - file: contact_us.qmd
        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

