project:
  type: website
  output-dir: docs

website:
  title: "IDEANet"
  back-to-top-navigation: True
  navbar:
    pinned: False
    left:
      - href: index.qmd
      - href: vignette.qmd
      - href: data_storage.qmd
      - href: contact_us.qmd
        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

