project:
  type: website
  output-dir: docs

website:
  title: "IDEANet"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: vignette.qmd
        text: R Vignette
      - href: contact_us.qmd
        text: Contact Us

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

